島嶼升級材料:
  第二級:
    物品:
      - '1:0:1'
      - '273:0:1'
    錢幣: 100
  第三級:
    物品:
      - '1:0:1'
      - '2:0:1'
      - '273:0:1'
    錢幣: 100
  第四級:
    物品:
      - '1:0:1'
      - '2:0:1'
      - '273:0:1'
      - '274:0:1'
    錢幣: 100
島嶼最大成員數量:
  第一級: 3
  第二級: 5
  第三級: 10
  第四級: 15